Repository coze-dev/coze-py, pull requests merged in 2024-10, with the labels that each got.

#53 chore: Update automated release configuration
  .github/release-drafter.yml
  .github/workflows/required-labels.yml
Labels: chore

#52 chore: Release v0.2.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#55 feat: Add async support with httpx.AsyncClient and refactor HTTP clients
  .gitignore
  codecov.yml
  cozepy/__init__.py
  cozepy/coze.py
  cozepy/request.py
  poetry.lock
  pyproject.toml
  tests/test_request.py
Labels: feature

#56 feat: Add AsyncStream and async clients for all async interfaces
  README.md
  codecov.yml
  cozepy/__init__.py
  cozepy/auth/__init__.py
  cozepy/bots/__init__.py
  cozepy/chat/__init__.py
  cozepy/chat/message/__init__.py
  cozepy/conversations/__init__.py
  cozepy/conversations/message/__init__.py
  cozepy/coze.py
  cozepy/files/__init__.py
  cozepy/knowledge/__init__.py
  cozepy/knowledge/documents/__init__.py
  cozepy/model.py
  cozepy/request.py
  cozepy/util.py
  cozepy/workflows/__init__.py
  cozepy/workflows/runs/__init__.py
  cozepy/workspaces/__init__.py
  tests/test_auth.py
  tests/test_bot.py
  tests/test_chat.py
  tests/test_chat_message.py
  tests/test_conversation.py
  tests/test_conversation_message.py
  tests/test_file.py
  tests/test_knowledge_documents.py
  tests/test_model.py
  tests/test_util.py
  tests/test_workflow.py
  tests/test_workspace.py
Labels: feature

#57 chore: Correct type annotation for Iterable of T
  cozepy/request.py
Labels: chore

#58 refactor: Refactor CozePKCEAuthError to use CozePKCEAuthErrorType Enum
  cozepy/__init__.py
  cozepy/auth/__init__.py
  cozepy/exception.py
  cozepy/request.py
  tests/test_auth.py
  tests/test_exception.py
Labels: chore

#60 chore: Correct type annotation to accurately identify
  cozepy/chat/message/__init__.py
  cozepy/knowledge/documents/__init__.py
  cozepy/request.py
Labels: chore

#62 docs: Update README to include usage instructions for stream and async
  README.md
  cozepy/bots/__init__.py
Labels: documentation

#63 chore: Release v0.3.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#65 perf: Optimize async iterator to eliminate the need for await
  README.md
  cozepy/chat/__init__.py
  cozepy/model.py
  cozepy/workflows/runs/__init__.py
  tests/test_chat.py
  tests/test_workflow.py
Labels: feature

#66 feat: Add iteration support to paginator
  README.md
  cozepy/__init__.py
  cozepy/bots/__init__.py
  cozepy/conversations/message/__init__.py
  cozepy/knowledge/documents/__init__.py
  cozepy/model.py
  cozepy/request.py
  cozepy/workspaces/__init__.py
  tests/test_bot.py
  tests/test_conversation_message.py
  tests/test_knowledge_documents.py
  tests/test_model.py
  tests/test_workflow.py
  tests/test_workspace.py
Labels: feature

#67 fix: Handle errors for chat.failed scenarios
  cozepy/__init__.py
  cozepy/auth/__init__.py
  cozepy/chat/__init__.py
  cozepy/exception.py
  cozepy/model.py
  cozepy/workflows/runs/__init__.py
  tests/test_chat.py
  tests/test_exception.py
  tests/test_model.py
Labels: bug

#68 refactor: Change upload file parameter from str to Union[Path]
  cozepy/files/__init__.py
  tests/test_file.py
Labels: feature

#69 chore: Release v0.4.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#70 refactor: Standardize and enhance various components
  README.md
  cozepy/auth/__init__.py
  cozepy/chat/__init__.py
  cozepy/files/__init__.py
  cozepy/knowledge/documents/__init__.py
  pyproject.toml
  tests/test_auth.py
  tests/test_chat.py
  tests/test_chat_message.py
  tests/test_conversation_message.py
  tests/test_knowledge_documents.py
Labels: feature

#71 docs: Add examples directory and update README
  README.md
  cozepy/knowledge/documents/__init__.py
  examples/auth_oauth_device.py
  examples/auth_oauth_jwt.py
  examples/auth_oauth_pkce.py
  examples/auth_oauth_web.py
  examples/auth_pat.py
  examples/bot_publish.py
  examples/chat_multimode_stream.py
  examples/chat_no_stream.py
  examples/chat_stream.py
  examples/exception.py
  examples/log.py
  examples/workflow_no_stream.py
  examples/workflow_stream.py
  tests/test_knowledge_documents.py
Labels: documentation

#72 docs: Update README
  README.md
  examples/log.py
Labels: documentation

#73 chore: Release v0.5.0
  README.md
  cozepy/version.py
  pyproject.toml
Labels: chore

#74 fix: Resolve dependency issue with httpx in higher Python versions
  examples/chat_multimode_stream.py
  poetry.lock
  pyproject.toml
Labels: bug

#75 docs: Update README with additional explanations
  README.md
  examples/bot_publish.py
  examples/chat_multimode_stream.py
  examples/chat_no_stream.py
  examples/chat_stream.py
  examples/exception.py
  examples/log.py
  examples/workflow_no_stream.py
  examples/workflow_stream.py
Labels: documentation

#79 docs: Add instructions for setting base_url in examples and README
  README.md
  examples/auth_oauth_device.py
  examples/auth_oauth_jwt.py
  examples/auth_oauth_pkce.py
  examples/auth_oauth_web.py
  examples/auth_pat.py
  examples/bot_publish.py
  examples/chat_multimode_stream.py
  examples/chat_no_stream.py
  examples/chat_stream.py
  examples/exception.py
  examples/workflow_no_stream.py
  examples/workflow_stream.py
  tests/test_workspace.py
Labels: documentation

#80 docs: Add examples and README instructions for configuring timeout
  README.md
  examples/timeout.py
Labels: documentation

#82 feat: Add required_action and usage to Chat object
  README.md
  cozepy/__init__.py
  cozepy/chat/__init__.py
  cozepy/model.py
  examples/chat_no_stream.py
  examples/chat_stream.py
  tests/test_chat.py
Labels: feature

#85 fix: Fix `build_user_question_objects` method in Message
  cozepy/chat/__init__.py
Labels: bug

#86 fix: Handle json errors in streaming api
  cozepy/request.py
  tests/config.py
  tests/test_chat.py
  tests/test_workflow.py
Labels: bug

#87 fix: Fix chat.stream api for streaming responses
  cozepy/request.py
  examples/chat_multimode_stream.py
  examples/chat_no_stream.py
  examples/chat_stream.py
Labels: bug

#91 fix: Fix field name in ChatToolCallFunction from 'argument' to 'arguments'
  cozepy/chat/__init__.py
Labels: bug

#90 fix: Resolve httpx.ResponseNotRead error in stream mode
  cozepy/request.py
Labels: bug

#92 chore: Release v0.6.1
  cozepy/version.py
  pyproject.toml
Labels: chore

#95 fix: Fix chat api conversation parameter and Release v0.6.2
  cozepy/chat/__init__.py
  cozepy/version.py
  examples/chat_conversation_stream.py
  pyproject.toml
Labels: bug

#94 docs: Add example on how to use local plugin and update README
  README.md
  examples/chat_local_plugin.py
Labels: documentation

#96 feat: Add API for creating room
  cozepy/__init__.py
  cozepy/coze.py
  cozepy/rooms/__init__.py
  tests/test_room.py
Labels: feature

#97 test: Add asynchronous tests for room API
  tests/test_room.py
Labels: chore

#100 fix: Fix HTTP method for chat message list
  cozepy/chat/message/__init__.py
  tests/test_chat.py
  tests/test_chat_message.py
Labels: bug

#101 docs: Update JWT OAuth usage example
  examples/auth_oauth_jwt.py
Labels: documentation

#102 feat: Add async execution to workflow and history retrieval
  README.md
  cozepy/__init__.py
  cozepy/request.py
  cozepy/workflows/runs/__init__.py
  cozepy/workflows/runs/run_histories/__init__.py
  examples/workflow_async.py
  tests/test_workflow.py
Labels: feature
