Repository coze-dev/coze-py, pull requests merged in 2024-11, with the labels that each got.

#104 docs: Update JWT OAuth usage example
  examples/auth_oauth_jwt.py
Labels: documentation

#103 feat: Add section_id field to conversation and message structures
  README.md
  cozepy/chat/__init__.py
  cozepy/conversations/__init__.py
  examples/conversation.py
  tests/test_conversation.py
Labels: feature

#105 refactor: Move RoomsClient to audio subdirectory as a subresource of AudioClient
  cozepy/__init__.py
  cozepy/audio/__init__.py
  cozepy/audio/rooms/__init__.py
  cozepy/coze.py
  tests/test_audio_rooms.py
Labels: feature

#106 feat: Add voice list retrieval API and upgrade NumberPaged
  cozepy/__init__.py
  cozepy/audio/__init__.py
  cozepy/audio/voices/__init__.py
  cozepy/bots/__init__.py
  cozepy/knowledge/documents/__init__.py
  cozepy/model.py
  cozepy/workspaces/__init__.py
  examples/audio.py
  tests/test_audio_voices.py
Labels: feature

#107 feat: Add speech create API with FileHTTPResponse support
  cozepy/__init__.py
  cozepy/audio/__init__.py
  cozepy/audio/rooms/__init__.py
  cozepy/audio/speech/__init__.py
  cozepy/chat/__init__.py
  cozepy/knowledge/documents/__init__.py
  cozepy/model.py
  cozepy/request.py
  cozepy/workflows/runs/__init__.py
  examples/audio.py
  tests/test_audio_speech.py
Labels: feature

#109 perf: Optimize base_url configuration by removing trailing slash
  cozepy/audio/__init__.py
  cozepy/audio/rooms/__init__.py
  cozepy/audio/speech/__init__.py
  cozepy/audio/voices/__init__.py
  cozepy/auth/__init__.py
  cozepy/bots/__init__.py
  cozepy/chat/__init__.py
  cozepy/chat/message/__init__.py
  cozepy/conversations/__init__.py
  cozepy/conversations/message/__init__.py
  cozepy/coze.py
  cozepy/files/__init__.py
  cozepy/knowledge/__init__.py
  cozepy/knowledge/documents/__init__.py
  cozepy/util.py
  cozepy/workflows/__init__.py
  cozepy/workflows/runs/__init__.py
  cozepy/workflows/runs/run_histories/__init__.py
  cozepy/workspaces/__init__.py
  tests/test_util.py
Labels: feature

#111 docs: Add example for workspace list API
  README.md
  examples/auth_oauth_device.py
  examples/workspace.py
Labels: documentation

#112 feat: Support audio messages in /v3/chat API
  README.md
  cozepy/__init__.py
  cozepy/audio/speech/__init__.py
  cozepy/chat/__init__.py
  cozepy/request.py
  cozepy/util.py
  examples/chat_audio.py
  tests/test_chat.py
  tests/testdata/chat_audio_stream_resp.txt
Labels: feature

#115 feat: Add voice cloning API
  cozepy/audio/speech/__init__.py
  cozepy/audio/voices/__init__.py
  cozepy/model.py
  examples/audio.py
  examples/chat_oneonone_audio.py
  examples/chat_simple_audio.py
Labels: feature

#117 feat: Support bot publish to WebSDK
  cozepy/bots/__init__.py
  examples/bot_publish.py
Labels: feature

#119 feat: Support passing conversation ID when creating a room
  cozepy/audio/rooms/__init__.py
  cozepy/chat/__init__.py
  tests/config.py
  tests/test_chat.py
Labels: feature

#121 chore: Release v0.7.0
  cozepy/version.py
  pyproject.toml
Labels: chore
