Repository coze-dev/coze-py, pull requests merged in 2024-12, with the labels that each got.

#125 feat: Enhance JWTAuth to Support Direct JWTOAuthApp Instance && Opt Examples
  cozepy/auth/__init__.py
  examples/auth_oauth_jwt.py
Labels: feature

#126 fix: Correct conversation_id parameter placement in chat API
  cozepy/chat/__init__.py
Labels: bug

#127 chore: Add VSCode settings configuration file
  .vscode/settings.json
Labels: chore

#128 fix: Update chat.cancel API to use body instead of params
  cozepy/chat/__init__.py
Labels: bug

#129 chore: Release v0.8.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#131 feat: Add sample_rate parameter support to audio speech API
  cozepy/audio/speech/__init__.py
  tests/test_audio_speech.py
Labels: feature

#133 feat: Implement template duplicate API with tests and examples
  cozepy/__init__.py
  cozepy/coze.py
  cozepy/templates/__init__.py
  examples/cli.py
  examples/template_duplicate.py
  tests/test_template.py
Labels: feature

#134 feat: Added dataset-related APIs
  .vscode/settings.json
  cozepy/__init__.py
  cozepy/datasets/__init__.py
  cozepy/datasets/documents/__init__.py
  cozepy/datasets/images/__init__.py
  cozepy/model.py
  cozepy/request.py
  examples/bot_publish.py
  examples/cli.py
  examples/dataset_create.py
  tests/test_bots.py
  tests/test_chat.py
  tests/test_chat_messages.py
  tests/test_conversations.py
  tests/test_conversations_messages.py
  tests/test_datasets.py
  tests/test_datasets_images.py
Labels: feature

#135 refactor: Implement logid return and standardize API responses
  cozepy/__init__.py
  cozepy/bots/__init__.py
  cozepy/chat/__init__.py
  cozepy/chat/message/__init__.py
  cozepy/datasets/__init__.py
  cozepy/datasets/documents/__init__.py
  cozepy/datasets/images/__init__.py
  cozepy/model.py
  cozepy/request.py
  examples/cli.py
  tests/config.py
  tests/test_audio_rooms.py
  tests/test_audio_speech.py
  tests/test_audio_voices.py
  tests/test_auth.py
  tests/test_bots.py
  tests/test_chat.py
  tests/test_chat_messages.py
  tests/test_conversations.py
  tests/test_conversations_messages.py
  tests/test_datasets.py
  tests/test_datasets_documents.py
  tests/test_datasets_images.py
  tests/test_file.py
  tests/test_model.py
  tests/test_request.py
  tests/test_util.py
  tests/test_workflow.py
  tests/test_workflows.py
  tests/test_workspace.py
  tests/test_workspaces.py
  tests/testdata/chat_error_resp.txt
  tests/testdata/chat_failed_resp.txt
  tests/testdata/chat_invalid_resp.txt
  tests/testdata/chat_text_stream_resp.txt
  tests/testdata/workflow_run_invalid_stream_resp.txt
  tests/testdata/workflow_run_stream_resp.txt
Labels: feature

#138 refactor: Enhance logid implementation using httpx.Response properties
  .coderabbit.yaml
  cozepy/chat/__init__.py
  cozepy/model.py
  cozepy/request.py
  cozepy/workflows/runs/__init__.py
  cozepy/workflows/runs/run_histories/__init__.py
  tests/test_audio_rooms.py
  tests/test_audio_speech.py
  tests/test_audio_voices.py
  tests/test_bots.py
  tests/test_chat.py
  tests/test_conversations.py
  tests/test_conversations_messages.py
  tests/test_datasets_documents.py
  tests/test_file.py
  tests/test_model.py
  tests/test_util.py
  tests/test_workflows.py
Labels: feature

#139 feat: Add support for custom UID when creating RTC room
  cozepy/audio/rooms/__init__.py
Labels: feature

#140 feat: Enhance file upload with multiple parameter options
  cozepy/files/__init__.py
  examples/cli.py
  tests/test_file.py
Labels: feature

#141 refactor: Optimize logid usage
  cozepy/chat/__init__.py
  cozepy/model.py
  cozepy/workflows/runs/__init__.py
  cozepy/workflows/runs/run_histories/__init__.py
  tests/test_chat.py
  tests/test_model.py
  tests/test_util.py
  tests/test_workflows.py
Labels: feature

#143 feat: Add ASR voice API for audio translation
  cozepy/__init__.py
  cozepy/audio/__init__.py
  cozepy/audio/translations/__init__.py
  tests/test_audio_translations.py
Labels: feature

#144 refactor: Rename 'res' to 'resp' in return values
  cozepy/__init__.py
  cozepy/audio/rooms/__init__.py
  cozepy/audio/translations/__init__.py
  cozepy/bots/__init__.py
  cozepy/datasets/__init__.py
  cozepy/templates/__init__.py
  examples/cli.py
  tests/test_audio_rooms.py
  tests/test_template.py
Labels: feature

#145 refactor: Restructure logid system for unified access through HTTPResponse
  cozepy/model.py
  cozepy/request.py
  cozepy/workflows/runs/run_histories/__init__.py
  tests/test_audio_rooms.py
  tests/test_audio_speech.py
  tests/test_audio_translations.py
  tests/test_audio_voices.py
  tests/test_bots.py
  tests/test_chat.py
  tests/test_chat_messages.py
  tests/test_conversations.py
  tests/test_conversations_messages.py
  tests/test_datasets.py
  tests/test_datasets_documents.py
  tests/test_datasets_images.py
  tests/test_file.py
  tests/test_workflows.py
Labels: chore

#146 feat: Add workflow chat API with tests and usage examples
  README.md
  cozepy/chat/__init__.py
  cozepy/model.py
  cozepy/request.py
  cozepy/util.py
  cozepy/workflows/__init__.py
  cozepy/workflows/chat/__init__.py
  examples/workflow_chat_stream.py
  tests/test_workflows_chat.py
  tests/testdata/workflows_chat_stream_resp.txt
Labels: feature

#147 docs: Add example for multimodal data chat using workflow
  README.md
  examples/workflow_chat_multimode_stream.py
Labels: chore

#150 docs: Add README explaining logid usage
  README.md
  cozepy/model.py
  tests/test_chat.py
  tests/test_workflows.py
  tests/test_workflows_chat.py
Labels: chore

#149 release: Bump version to 0.9.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#151 chore: Update parameters type annotation in workflows.chat and Bump version to 0.9.1
  cozepy/version.py
  cozepy/workflows/chat/__init__.py
  pyproject.toml
Labels: chore

#152 feat: Add description and space_id parameters to voices.clone api
  cozepy/audio/voices/__init__.py
  tests/test_audio_voices.py
Labels: feature
