Repository coze-dev/coze-py, pull requests merged in 2025-07, with the labels that each got.

#286 fix: Fix reusing http connections
  cozepy/chat/__init__.py
  cozepy/model.py
  cozepy/workflows/chat/__init__.py
  cozepy/workflows/runs/__init__.py
  tests/test_model.py
Labels: bug

#275 feat: Add data field for ConversationChatCanceledEvent
  cozepy/websockets/chat/__init__.py
Labels: feature

#281 feat: Add enterprises.members api
  cozepy/__init__.py
  cozepy/bots/__init__.py
  cozepy/coze.py
  cozepy/enterprises/__init__.py
  cozepy/enterprises/members/__init__.py
  cozepy/util.py
  pyproject.toml
  tests/test_enterprises_members.py
  tests/test_util.py
Labels: feature

#287 feat: Add device_id parameter for websockets.chat
  cozepy/websockets/chat/__init__.py
Labels: feature

#268 feat: Add conversations.messages.feedback api
  cozepy/__init__.py
  cozepy/conversations/message/__init__.py
  cozepy/conversations/message/feedback/__init__.py
  tests/test_conversations_messages_feedback.py
Labels: feature

#260 feat: Add api_apps and api_apps.events api
  cozepy/__init__.py
  cozepy/api_apps/__init__.py
  cozepy/api_apps/events/__init__.py
  cozepy/coze.py
  cozepy/model.py
  tests/test_api_apps.py
  tests/test_bots.py
Labels: feature

#292 fix: Handle the compatibility issue when suggested_questions is empty
  cozepy/bots/__init__.py
Labels: bug

#293 chore: Bump version to 0.18.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#295 feat: Add input_text.generate_audio event for WebSocket chat API
  cozepy/__init__.py
  cozepy/websockets/chat/__init__.py
  cozepy/websockets/ws.py
Labels: feature

#299 feat: Add unpublish agent API implementation
  cozepy/bots/__init__.py
  examples/bot_unpublish.py
  tests/test_bots.py
Labels: feature

#300 feat: Support usage for workflow run
  cozepy/request.py
  cozepy/workflows/runs/__init__.py
  cozepy/workflows/runs/run_histories/__init__.py
Labels: feature

#306 feat: Add is_output_trimmed field to WorkflowRunHistory model
  cozepy/workflows/runs/run_histories/__init__.py
  tests/test_workflow_run_history.py
  tests/test_workflows_runs.py
Labels: feature
