Repository coze-dev/coze-py, pull requests merged in 2025-01, with the labels that each got.

#158 refactor: Rename 'translations' to 'transcriptions'
  cozepy/__init__.py
  cozepy/audio/__init__.py
  cozepy/audio/transcriptions/__init__.py
  tests/test_audio_translations.py
Labels: feature

#156 feat: Implement WebSocket support
  .coderabbit.yaml
  .gitignore
  cozepy/__init__.py
  cozepy/audio/voices/__init__.py
  cozepy/chat/__init__.py
  cozepy/coze.py
  cozepy/util.py
  cozepy/websockets/__init__.py
  cozepy/websockets/audio/__init__.py
  cozepy/websockets/audio/speech/__init__.py
  cozepy/websockets/audio/transcriptions/__init__.py
  cozepy/websockets/chat/__init__.py
  cozepy/websockets/ws.py
  cozepy/workflows/runs/__init__.py
  examples/chat_stream.py
  examples/utils/__init__.py
  examples/websockets_audio_speech.py
  examples/websockets_audio_transcriptions.py
  examples/websockets_chat.py
  poetry.lock
  pyproject.toml
  tests/test_conversations_messages.py
Labels: feature

#160 fix: Resolve WebSocket issues and add real-time call example
  .gitignore
  cozepy/chat/__init__.py
  cozepy/websockets/audio/speech/__init__.py
  cozepy/websockets/audio/transcriptions/__init__.py
  cozepy/websockets/chat/__init__.py
  cozepy/websockets/ws.py
  examples/websockets_chat_realtime_gui.py
Labels: bug

#162 feat: Enhance OAuth configuration and improve example scripts
  cozepy/__init__.py
  cozepy/auth/__init__.py
  examples/chat_stream.py
  examples/utils/__init__.py
  examples/websockets_audio_speech.py
  examples/websockets_audio_transcriptions.py
  examples/websockets_chat.py
  examples/websockets_chat_realtime_gui.py
Labels: chore

#163 fix: Fix client_type in load_oauth_app_from_config
  cozepy/auth/__init__.py
Labels: chore

#164 release: Bump version to 0.10.1
  cozepy/version.py
  pyproject.toml
Labels: chore

#165 fix: Fix load_oauth & Bump version to 0.10.2
  cozepy/auth/__init__.py
  cozepy/version.py
  pyproject.toml
Labels: chore

#170 fix: CI fails on python 3.7
  .github/workflows/ci.yml
Labels: chore

#169 feat: Add inserted_additional_messages to chat response
  cozepy/chat/__init__.py
Labels: feature

#172 chore: Bump version to 0.10.4
  cozepy/version.py
  pyproject.toml
Labels: chore

#177 feat: Add v1/users/me API endpoint to retrieve current authorized user info
  cozepy/__init__.py
  cozepy/coze.py
  cozepy/users/__init__.py
  examples/users_me.py
  tests/test_users.py
Labels: feature

#180 feat: add missed app_id for workflow
  cozepy/workflows/runs/__init__.py
Labels: feature
