Repository coze-dev/coze-py, pull requests merged in 2025-04, with the labels that each got.

#213 fix: Fix resume workflow key
  cozepy/workflows/runs/__init__.py
Labels: bug

#216 chore: Update README.md
  README.md
Labels: chore

#201 feat: Enhance event handling system with dynamic inspect
  cozepy/util.py
  cozepy/websockets/audio/speech/__init__.py
  cozepy/websockets/audio/transcriptions/__init__.py
  cozepy/websockets/chat/__init__.py
  cozepy/websockets/ws.py
Labels: feature

#210 feat: Support send `conversation.message.create` websocket event
  cozepy/websockets/chat/__init__.py
  cozepy/websockets/ws.py
Labels: feature

#212 feat: Support sync coze websocket client
  cozepy/coze.py
Labels: feature

#217 chore: Update README.md
  README.md
Labels: chore

#218 chore: Update Examples
  examples/audio.py
  examples/auth_oauth_device.py
  examples/auth_oauth_jwt.py
  examples/auth_oauth_pkce.py
  examples/auth_oauth_web.py
  examples/auth_pat.py
  examples/benchmark_text_chat.py
  examples/benchmark_websockets_chat.py
  examples/bot_publish.py
  examples/chat_conversation_stream.py
  examples/chat_local_plugin.py
  examples/chat_multimode_stream.py
  examples/chat_no_stream.py
  examples/chat_oneonone_audio.py
  examples/chat_simple_audio.py
  examples/chat_stream.py
  examples/conversation.py
  examples/conversation_list.py
  examples/dataset_create.py
  examples/exception.py
  examples/files_upload.py
  examples/template_duplicate.py
  examples/timeout.py
  examples/users_me.py
  examples/websockets_audio_speech.py
  examples/websockets_audio_transcriptions.py
  examples/websockets_chat.py
  examples/workflow_async.py
  examples/workflow_chat_multimode_stream.py
  examples/workflow_chat_stream.py
  examples/workflow_no_stream.py
  examples/workflow_stream.py
  examples/workspace.py
Labels: chore

#219 feat: Support SuggestReply for create, update and retrieve bot
  cozepy/__init__.py
  cozepy/bots/__init__.py
  examples/bot_create.py
  examples/bot_retrieve.py
  examples/bot_update.py
Labels: feature

#220 feat: Support retrieve bot background image
  cozepy/__init__.py
  cozepy/bots/__init__.py
  examples/users_me.py
Labels: feature

#221 feat: Support retrieve bot variable meta
  cozepy/__init__.py
  cozepy/bots/__init__.py
Labels: feature

#222 fix: Fix variable key
  cozepy/bots/__init__.py
Labels: bug

#223 fix: Add 'data' field of type Message to ConversationMessageCompletedEvent class
  cozepy/websockets/chat/__init__.py
Labels: bug

#226 fix: Fix parsing of WorkflowRunHistory in running state
  cozepy/workflows/runs/run_histories/__init__.py
  tests/test_workflow_run_history.py
Labels: bug

#231 chore: Fix import error in README.md
  README.md
Labels: chore
