Repository coze-dev/coze-py, pull requests merged in 2025-02, with the labels that each got.

#176 feat: Update bot api support knowledge
  cozepy/__init__.py
  cozepy/bots/__init__.py
Labels: feature

#181 feat: Add app_id support to workflow
  cozepy/workflows/runs/__init__.py
  examples/workflow_async.py
  examples/workflow_stream.py
  tests/test_workflows.py
Labels: feature

#182 chore: Bump version to 0.12.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#184 feat: Add async JWT support with session_name
  cozepy/auth/__init__.py
  examples/files_upload.py
Labels: feature

#183 fix: Resolve logger overriding global log configuration
  cozepy/log.py
Labels: bug

#186 feat: Add support for deepseek model reasoning_content
  cozepy/chat/__init__.py
  examples/chat_stream.py
Labels: feature
