Repository coze-dev/coze-py, pull requests merged in 2025-05, with the labels that each got.

#233 feat: Support parameters for chat
  cozepy/chat/__init__.py
  examples/chat_stream.py
Labels: feature

#234 feat: Support variable API
  README.md
  cozepy/__init__.py
  cozepy/coze.py
  cozepy/variables/__init__.py
  examples/variable_retrieve.py
  examples/variable_update.py
Labels: feature

#235 chore: Bump version to 0.15.0
  cozepy/version.py
  pyproject.toml
Labels: chore

#239 fix: Fix recv blocking when sync-websocket is closed
  cozepy/version.py
  cozepy/websockets/ws.py
  pyproject.toml
Labels: bug

#244 fix: Fix atomicity issue in create_and_poll
  cozepy/chat/__init__.py
  examples/chat_no_stream.py
Labels: bug

#245 chore: Fix README typo
  README.md
Labels: chore

#248 chore: Update benchmark websocket examplpe
  README.md
  examples/auth_pat.py
  examples/benchmark_websockets_chat.py
Labels: chore
